Le profit maximal apres 6 mois: 107843 (euros)
Au mois 1 :
  Pour l'huile V1 :
    Acheter : 0 tonne(s)
    Raffiner : 159 tonne(s)
    Stocker : 341 tonne(s)
  Pour l'huile V2 :
    Acheter : 0 tonne(s)
    Raffiner : 41 tonne(s)
    Stocker : 459 tonne(s)
  Pour l'huile H1 :
    Acheter : 0 tonne(s)
    Raffiner : 0 tonne(s)
    Stocker : 500 tonne(s)
  Pour l'huile H2 :
    Acheter : 0 tonne(s)
    Raffiner : 250 tonne(s)
    Stocker : 250 tonne(s)
  Pour l'huile H3 :
    Acheter : 0 tonne(s)
    Raffiner : 0 tonne(s)
    Stocker : 500 tonne(s)
Au mois 2 :
  Pour l'huile V1 :
    Acheter : 0 tonne(s)
    Raffiner : 159 tonne(s)
    Stocker : 181 tonne(s)
  Pour l'huile V2 :
    Acheter : 0 tonne(s)
    Raffiner : 41 tonne(s)
    Stocker : 419 tonne(s)
  Pour l'huile H1 :
    Acheter : 0 tonne(s)
    Raffiner : 0 tonne(s)
    Stocker : 500 tonne(s)
  Pour l'huile H2 :
    Acheter : 250 tonne(s)
    Raffiner : 250 tonne(s)
    Stocker : 250 tonne(s)
  Pour l'huile H3 :
    Acheter : 0 tonne(s)
    Raffiner : 0 tonne(s)
    Stocker : 500 tonne(s)
Au mois 3 :
  Pour l'huile V1 :
    Acheter : 0 tonne(s)
    Raffiner : 159 tonne(s)
    Stocker : 22 tonne(s)
  Pour l'huile V2 :
    Acheter : 0 tonne(s)
    Raffiner : 41 tonne(s)
    Stocker : 378 tonne(s)
  Pour l'huile H1 :
    Acheter : 0 tonne(s)
    Raffiner : 0 tonne(s)
    Stocker : 500 tonne(s)
  Pour l'huile H2 :
    Acheter : 0 tonne(s)
    Raffiner : 250 tonne(s)
    Stocker : 0 tonne(s)
  Pour l'huile H3 :
    Acheter : 0 tonne(s)
    Raffiner : 0 tonne(s)
    Stocker : 500 tonne(s)
Au mois 4 :
  Pour l'huile V1 :
    Acheter : 0 tonne(s)
    Raffiner : 22 tonne(s)
    Stocker : 0 tonne(s)
  Pour l'huile V2 :
    Acheter : 0 tonne(s)
    Raffiner : 178 tonne(s)
    Stocker : 200 tonne(s)
  Pour l'huile H1 :
    Acheter : 0 tonne(s)
    Raffiner : 0 tonne(s)
    Stocker : 500 tonne(s)
  Pour l'huile H2 :
    Acheter : 0 tonne(s)
    Raffiner : 0 tonne(s)
    Stocker : 0 tonne(s)
  Pour l'huile H3 :
    Acheter : 0 tonne(s)
    Raffiner : 250 tonne(s)
    Stocker : 250 tonne(s)
Au mois 5 :
  Pour l'huile V1 :
    Acheter : 0 tonne(s)
    Raffiner : 0 tonne(s)
    Stocker : 0 tonne(s)
  Pour l'huile V2 :
    Acheter : 0 tonne(s)
    Raffiner : 200 tonne(s)
    Stocker : 0 tonne(s)
  Pour l'huile H1 :
    Acheter : 0 tonne(s)
    Raffiner : 0 tonne(s)
    Stocker : 500 tonne(s)
  Pour l'huile H2 :
    Acheter : 0 tonne(s)
    Raffiner : 0 tonne(s)
    Stocker : 0 tonne(s)
  Pour l'huile H3 :
    Acheter : 500 tonne(s)
    Raffiner : 250 tonne(s)
    Stocker : 500 tonne(s)
Au mois 6 :
  Pour l'huile V1 :
    Acheter : 659 tonne(s)
    Raffiner : 159 tonne(s)
    Stocker : 500 tonne(s)
  Pour l'huile V2 :
    Acheter : 541 tonne(s)
    Raffiner : 41 tonne(s)
    Stocker : 500 tonne(s)
  Pour l'huile H1 :
    Acheter : 0 tonne(s)
    Raffiner : 0 tonne(s)
    Stocker : 500 tonne(s)
  Pour l'huile H2 :
    Acheter : 750 tonne(s)
    Raffiner : 250 tonne(s)
    Stocker : 500 tonne(s)
  Pour l'huile H3 :
    Acheter : 0 tonne(s)
    Raffiner : 0 tonne(s)
    Stocker : 500 tonne(s)
